### ISSUE TITLE
a question regarding the formulat getting delta

### ISSUE THREAD

**Issue by zhchyang2004** [betaBison/gnss-sensor-fusion#1]
Hi,
 
In 'def least_squares' of gnss_only_ekf.py,  how to undestand the current formular of getting delta?

Do you think it more reasonable to change the formular from
'delta = np.linalg.pinv(W.dot(G)).dot(W).dot(rho_dif)'
to 
'delta = np.linalg.inv(G.T.dot(W).dot(G)).dot(G.T).dot(W).dot(rho_dif) ' ?

**Comment by betaBison** [comment]
Hi @zhchyang2004! Check out [this function](https://github.com/google/gps-measurement-tools/blob/master/opensource/WlsPvt.m#L102) from Google's GNSS Analysis app. Their code is commented much better too!

**Comment by zhchyang2004** [comment]
Hi,

Thank you for kind feedback. I'v studied it. According to their logic, the current formular is from this: W.dot(G).dot(delta)=W.dot(rho_dif)

W as defined, is the inverse of 'Pr_sigma', related to psuedorange, instead of the state parameter x_0 and bu.   But, 'W.dot(G).dot(delta)'  means W is related to delta. I'm so confused by this setting. 

Could you please share your idea on it?

Thanks!

**Comment by betaBison** [comment]
Is your question about pinv? Your proposed formula is algebraically equivalent.  
The current method is:
![method_1](https://user-images.githubusercontent.com/23247972/82921313-18677700-9f2d-11ea-9d0f-aa39b7f6c14b.png)
And you're proposing:
![method2](https://user-images.githubusercontent.com/23247972/82921382-2ae1b080-9f2d-11ea-9491-c599bfd9fa17.png)
I think you want to use the psuedoinverse (pinv) in case the matrix is close to singular. You can also check with:
```
W = np.random.rand(12,12)
G = np.random.rand(12,12)
np.allclose(np.linalg.pinv(W.dot(G)),np.linalg.inv(G.T.dot(W).dot(G)).dot(G.T))
```

**Comment by zhchyang2004** [comment]
Hi, 

When G is a square matrix, both results are equivalent. If G is not a square matrix, they are not equivalent, i.e. G = np.random.rand(11,4) in the project.

If you take the least square as a graph slam problem, you can understand my proposal.  W[ii,ii] can be regarded as an information value from each measurement. 

My doubt is about the W's function in 'W.dot(G).dot(delta)'.  It is hard to explain it according to W's definition.

Thank you!

**Comment by betaBison** [comment]
I don't have any additional insight for you. Since we pulled the equation you're referencing from [gps-measurement-tools](https://github.com/google/gps-measurement-tools), I'd suggest asking there. Best of luck.
